# see: https://github.com/electron/spectron/blob/master/appveyor.yml

build: off

os: unstable

platform:
  - x64
  - x86

version: "{build}"

skip_tags: true
clone_folder: c:\projects\storyboarder
clone_depth: 10

environment:
  global:
    NODE_VERSION: 8.4.0

  matrix:
  - TASK: test

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  # use 4.6.1 because: https://github.com/npm/npm/issues/17747
  - npm install -g npm@4.6.1
  - npm install
  - npm install 7zip-bin-win

test_script:
  - node --version
  - npm --version
  - npm test
  # build the binary so we can test it
  - npm run pack
  - tree /f
  - node ./node_modules/mocha/bin/mocha test/app/index.test.main.js

deploy: off

cache:
  - '%APPVEYOR_BUILD_FOLDER%\electron'
  - node_modules -> package.json
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'